---
title           : "My preregistration for Global High-resolution Water Temperature Modelling"
shorttitle      : "My preregistration"
date            : "`r Sys.setlocale('LC_TIME', 'C'); format(Sys.time(), '%d\\\\. %B %Y')`"

author: 
  - name        : Ziqian Han
    affiliation : 1
  - name        : Ernst-August Doelle
    affiliation : "1,2"

affiliation:
  - id          : 1
    institution : Wilhelm-Wundt-University
  - id          : 2
    institution : Konstanz Business School

output: prereg::prereg_pdf
---

<!-- To keep pre-registrations to a reasonable length for readers, we recommend answers fit within a single page .pdf document, roughly 3200 characters. Read more about this here: https://aspredicted.org/messages/why_limits.php -->


## Data collection
<!-- Have any data been collected for this study already? (Note: "Yes" is not an accepted answer.) -->

We have already collected global measured river temperature data and global air temperature
data for validation and model inputs.


## Dependent variable
<!-- Describe the key dependent variable(s) specifying how they will be measured. -->

> The dependent variable used in the model is the air temperature at the local watershed.


## Analyses
<!-- Specify exactly which analyses you will conduct to examine the main question/hypothesis. -->

> Global air temperature will be input into the model to estimate the river temperature of every river
reach documented in HydroSHEDS. Hydrologic stations with the low upstream basin areas will be used for
model calibration, the rest of the temperature observations will be used for validation.

## Outliers and exclusions
<!-- Describe exactly how outliers will be defined and handled, and your precise rule(s) for excluding observations. -->

> Observations with unreasonable temperature values will be excluded. To simplify the approach,
the observation will be defined as an outlier if all the twelve monthly temperatures are higher than
the air temperature.


## Study type
Finally. For record keeping purposes, please tell us the type of study you are pre-registering.

* This study is a Master's research thesis.
